* Dotfile Literate Configuration

This config is (so far) only for an MX Apple silicon machine.
Here in _the garden_ lies my digital self, amongst the bees and tings and flowers... and the wall...

Some aspects (hardware, talon) don't depend on Apple computer.
I includeese aspects here too -- dey considered part o my `config`.

Welcome to this document. It's written in the style of `literate programming`. (shout out Donald Knuth)
This document is an `Org` file. It ends with ".org". It's a mix of writing and code. Just some symbols...
For settin up me macheens, this file actively works as the "single source of truth".
Anytime I touch [configure] [change something] it is written --- here.

If ur readin in HTML browser, u only see de /basic/ code block.
irl (in emacs) the code blocks are *linked* to certain files. (aka `tangled`, ie automatic export)
You gotta read it in emacs to really see. One of these lifetimes, emacs will find you.

The tangle of code within these writings... It feels...
...as Donald said: [I'm paraphrasing]
#+begin_src story
    your code should tell a story
#+end_src

** Tools
*** hands & keyboard
Before install anyting... check ya hands an keys.
**** hands
touch type 1.0 accuracy. slow
backspace === push/pull-up
**** adv360
no cap labels. let the keys come to you
home-row-mods
colemak-dh
layers: base, nav, func, mod
***** layout
https://github.com/antoaenono/key-zmk-adv360pro

*** voice, face, eyes, body
talon

** Install
*** dotfiles

#+begin_src shell :tangle "install.sh"
git clone github.com/antoaenono/dotfiles.git ~/.local/share/chezmoi
#+end_src

*** Homebrew
...RIP MacPorts..? I'm too late to the game.

Install `homebrew` via blindly trusting script:
#+begin_src shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#+end_src

**** Notes
- creates a bunch of dirs
- installs xcode command line tools
- need to hit return to continue
- output message after installing xcode:
  Run these commands in your terminal to add Homebrew to your PATH:
      echo >> /Users/antoaenono/.zprofile
      echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/antoaenono/.zprofile
      eval "$(/opt/homebrew/bin/brew shellenv)"
  - Run brew help to get started
  - Further documentation:
      https://docs.brew.sh
  - type `brew` or `man brew` to learn more
*** chezmoi
#+begin_src shell
brew install chezmoi
#+end_src

** Configure
