echo "load zshrc"

# Aliases
source ~/.config/zsh/alias.zsh

# Functions
## Load at startup
source ~/.config/zsh/function.zsh
## Lazy loading every function file from a functions dir
#fpath=(~/.config/zsh/functions $fpath)
#autoload -Uz <fn_name>

# Bitwarden SSH Agent
export SSH_AUTH_SOCK=/Users/antoaenono/Library/Containers/com.bitwarden.desktop/Data/.bitwarden-ssh-agent.sock

# Tealdeer
export TEALDEER_CONFIG_DIR=/Users/antoaenono/.config/tealdeer

echo "loaded zshrc"
